# from quickstart:
# https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/kubernetes-examples/keycloak.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:

      # inserted
#      volumes:
#      - name: keycloak-hookvolume
#        configMap:
#          name: keycloak-configmap
#          defaultMode: 0755

      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:19.0.1
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
        # inserted
#        volumeMounts:
#          - mountPath: /opt/keycloak/bin/poststart.sh
#            subPath: poststart.sh
#            name: keycloak-hookvolume
#          - mountPath: /tmp/myclient.exported.json
#            subPath: myclient.exported.json
#            name: keycloak-hookvolume
