# Example of checking for symlink and removing
#
# Supporting blog entry:
# https://fabianlee.org/2021/03/02/ansible-deleting-a-file-path-but-only-if-a-symbolic-link/
#
# example:
#   ansible-playbook playbook-remove-symlink.yml --extra-vars "link_path=testlink"
#
---
- hosts: all
  become: no
  gather_facts: no

  vars:
    link_path: testlink

  tasks:

    - stat: 
        path: "{{link_path}}"
      register: link

    - debug: 
        msg: "does path {{link_path}} exist? {{link.stat.exists}} and is it link {{link.stat.islnk|default(false)}}"

    # only deletes if symbolic link
    - name: remove symlink
      file:
        path: "{{link_path}}"
        state: absent
      when: link.stat.islnk is defined and link.stat.islnk

