# shows how to use jinja2 ipaddr filter from ansible, needs 'netaddr' pip or package
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html
#
# prerequisite: install netaddr os package and galaxy collection:
#   ansible-playbook install_dependencies.yml
---
- hosts: localhost
  gather_facts: true

  vars:
  - IP: 172.31.3.13/23
  - CIDR: 192.168.0.0/16
  - MAC: 1a:2b:3c:4d:5e:6f
  - PREFIX: 18

  tasks:

    - debug: msg="___ {{ IP }} ___ ADDRESS {{ IP | ipaddr('address') }}"
    - debug: msg="___ {{ IP }} ___ BROADCAST {{ IP | ipaddr('broadcast') }}"
    - debug: msg="___ {{ IP }} ___ NETMASK {{ IP | ipaddr('netmask') }}"
    - debug: msg="___ {{ IP }} ___ NETWORK {{ IP | ipaddr('network') }}"
    - debug: msg="___ {{ IP }} ___ PREFIX {{ IP | ipaddr('prefix') }}"
    - debug: msg="___ {{ IP }} ___ SIZE {{ IP | ipaddr('size') }}"


    - debug: msg="first 3 octets of 192.168.1.114 = {{ "192.168.1.114".split('.')[0:3] | join('.') }}.xx"
