# Example of installing matching linux kernel headers for Ubuntu
#
# Supporting blog entry: https://fabianlee.org/2021/05/19/ansible-installing-linux-headers-matching-kernel-for-ubuntu/
#
# example:
#   ansible-playbook playbook-kernel-headers.yml
#
---
- hosts: all
  become: yes
  connection: local
  gather_facts: yes

  tasks:

  - name: install headers matching kernel
    apt:
      pkg:
      - linux-headers-{{ ansible_kernel }}

  - name: meta package that auto-matches kernel
    apt: 
      pkg:
      - linux-headers-generic

